/**
 * PRD Questionnaire Types
 */

export type { TemplateLevel } from "./prd-checklist";

export type UserMindset = "growth_focused" | "profit_focused" | "quality_focused" | "balanced";

export interface QuestionOption {
  label: string;
  value: string;
  description?: string;
}

export interface Question {
  id: string;
  question: string;
  type: "text" | "single_choice" | "multiple_choice";
  options?: QuestionOption[];
  followUpConditions?: Record<string, string>; // answer value -> followup question id
  placeholder?: string;
  isFollowUp?: boolean;
  parentQuestion?: string;
}

export interface Answer {
  questionId: string;
  value: string | string[]; // single value or multiple values
  text?: string; // user's actual text input
}

/**
 * Dynamic Question Generated by AI
 */
export interface DynamicQuestion {
  question: string;
  type: "text" | "single_choice" | "multiple_choice";
  options?: QuestionOption[];
  targetSection: string; // which PRD section this question fills
  rationale?: string; // why this question was chosen
}

/**
 * Conversation Context for Dynamic Question Generation
 */
export interface ConversationContext {
  originalIdea?: string; // User's FIRST description of the product idea (most important!)
  product?: string; // Product name/description
  problem?: string; // Core problem being solved
  target?: string; // Target users
  values?: string[]; // Core values collected so far
  userMindset?: UserMindset; // Inferred mindset from previous answers
}

/**
 * PRD Completeness Report
 */
export interface CompletenessReport {
  overallScore: number; // 0-100
  sections: {
    name: string;
    score: number; // 0-100
    missingFields: string[];
  }[];
  criticalGaps: string[]; // High priority missing fields
}

export interface PRDData {
  // 제품 개요 (Product Overview)
  productName?: string;
  productOneLine?: string;
  productVision?: string;
  productGoals?: string;
  productMission?: string;

  // 문제 정의 (Problem Definition)
  coreProblem?: string;
  problemImpact?: string[];
  existingSolution?: string;
  solutionLimitations?: string[];
  marketSize?: string;

  // 타겟 사용자 (Target Users)
  targetUsers?: string[];
  targetUserDetail?: string;
  personaPrimary?: string;
  personaSecondary?: string;

  // 경쟁 분석 (Competitive Analysis)
  competitors?: string[];
  competitiveAdvantage?: string;

  // 핵심 가치 제안 (Value Proposition)
  valueProposition?: string;
  coreValue?: string[];

  // 비즈니스 모델 (Business Model)
  businessModel?: string;
  freeTier?: string;
  pricing?: string;
  conversionStrategy?: string;
  revenueProjection?: string;
  unitEconomics?: string;

  // 핵심 기능 (Core Functions)
  coreFunctions?: string[];
  functionDescriptions?: Record<string, string>;
  functionPriority?: string;
  exceptionHandling?: string;

  // 사용자 플로우 (User Flow)
  userFlow?: string;
  onboarding?: string;

  // MVP 범위 (MVP Scope)
  mvpScope?: string;
  mvpFeatures?: string;

  // 성공 지표 (Success Metrics)
  successMetrics?: string[];
  metricTargets?: Record<string, string>;
  conversionFunnel?: string;

  // 출시 계획 (Launch Plan)
  launchTimeline?: string;
  milestones?: string;
  goToMarket?: string;

  // 리스크 및 대응 (Risks & Mitigation)
  risks?: string[];
  mitigation?: string;
}

export interface PRDQuestionnaireState {
  currentQuestionId: string;
  completedQuestions: string[];
  answers: Answer[];
  prdData: PRDData;
  prdContent: string; // Current PRD markdown content
  isComplete: boolean;
}
