/**
 * User Flow Agent Types
 */

/**
 * User answer to a question
 */
export interface Answer {
  questionId: string;
  questionText: string;
  answer: string;
  timestamp: Date;
}

/**
 * Dynamic question generated by AI
 */
export interface DynamicQuestion {
  id: string;
  questionText: string;
  choices?: string[];
  context?: string;
  isFollowUp?: boolean;
  parentQuestionId?: string;
}

/**
 * User flow context extracted from answers
 */
export interface UserFlowContext {
  // Screen structure
  totalScreens?: number;
  screenList?: Array<{ name: string; purpose: string }>;

  // First-time user flow
  hasOnboarding?: boolean;
  loginMethod?: string;
  splashDuration?: string;

  // Main screen
  mainScreenLayout?: string;
  mainScreenComponents?: string[];

  // Key features
  primaryAction?: string;
  navigationPattern?: string;

  // Business model
  hasFreemium?: boolean;
  pricingTrigger?: string;

  // Additional context
  [key: string]: any;
}

/**
 * Screen information for ASCII mockups
 */
export interface Screen {
  name: string;
  description: string;
  components: string[];
  layout?: string;
}

/**
 * User flow scenario
 */
export interface UserFlowScenario {
  title: string;
  goal: string;
  steps: string[];
}

/**
 * Complete user flow data structure
 */
export interface UserFlowData {
  // Screens
  screens: Screen[];

  // Text-based flows
  scenarios: UserFlowScenario[];

  // ASCII mockups
  asciiScreens: { [screenName: string]: string };

  // Mermaid diagram code
  mermaidDiagram: string;
}
